name: Build iOS Artifacts
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Build Framework
        run: |
          chmod +x gradlew
          ./gradlew :composeApp:assembleDebugFramework --stacktrace
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Najed-Express-iOS-Final
          path: "**/ComposeApp.framework"
